apiVersion: v1
kind: Config
clusters:
  - cluster:
      server: https://omni.koutoulastha.dev:8100/
    name: omni-main
contexts:
  - context:
      cluster: omni-main
      namespace: default
      user: omni-main-koutoulastha@hotmail.com
    name: omni-main
current-context: omni-main
users:
- name: omni-main-koutoulastha@hotmail.com
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
        - oidc-login
        - get-token
        - --oidc-issuer-url=https://omni.koutoulastha.dev/oidc
        - --oidc-client-id=native
        - --oidc-extra-scope=cluster:main
      command: kubectl
      env: null
      provideClusterInfo: false
