---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgC6sPTDnTtcuUTgzP+6yIM7X9c3gKbyb51Qu3UFs3KzPzQ6azbAdYfj5FaevRxXrdWU04qxESn2TRPEi+ughDT8tMGm4sUF0+0xjmg7GTE7i0JIg/1S+uZCp32QPeCXDCPaTVBeVlgy7WxZ8MVwArg/ZmoPwDGPvYAQO7RL9PHbqQoeVl1SeNuoD3G3KG1a9k5fSc205D3G3CCiWptWbrrux0GSv2nlF8rFXyKlrnnA6do62mfBJ4q9gotsk4YsVnfhtLfbLYfnxTkMB6ZzzQs2FGLp8fMVpQegXTE8B2r6I2NQHED47RBNgjveR67d8EBtSZJ3IRKYDZZd+ZpCsEQ3vbvmz/LhdNsHV+VzLNX5dCMn3CEEXBhq3TDZT+2HMXgIl81IqHHcONBloy//sGBstGm/dgcnowRKo3mmksDDfW/GpCj7m9uEV4nkA1NmxJAzkqeR7EJtoaf8QJ1igsyU1dvD+gR1GLD1oNhoP5rodjcp7UY4j2QpLQPznXtaykvEzbQb4C8czybaoB9RiJzVF612+j/bOaN7vcDzoSI3vdIaE2OwNLepLOE5884AQwrxWU0hRT0AwxEsSd92OKtIihEmejF0WVpufixVTIM9JDiYS2crm0hPKGkQHr6w0scJ9DEEOTFItMiFJDMTl3b0jyH5YfDAetJX4zjTxxUw9mvLA0bQ45LpRkLDIbon/nGG/23tYq72BQnLzJo=
    admin-user: AgC30pblpiwmCfR4MdhHHjP0z0W3jHranLAIME1E8n3e2Z5WxODylcgbkfdP5LrAsvQzBA6ysc4eyCOVSHUoMxiW4C101EUM06hXxzcuvzbaQ0n5nel2QTfb9WrhtrO+IsKJ9XgAFfpGtlr5Lzqf2+rOXtryzAgInB9okIfVlJSfaUddWpkwhj4anWKzDdL1LXyPtn6PNZIgZU+KISxqem/GmNND3Nk0tPzQeqWQXlqBIYQL+HevrpU8F6Xlwrkpt0/T5LJ7llvZkZ4icCqMK5gZE0dYcGBsXn9zmo7xUpbqZkmwCsvj54mz4hGR1mk7j8Xcz5DfJFqEfylBol2VA6phMtLtZoUvSZbGiDnl7MtsCeHnIkJTI004ie7cAY+I8QR4SLYo4dYWwMLMBn6GjRTk7C+gOSnKDNcpK5OCH6n7eV0He1I+rjqBBFAJYrZWdRuCEXdSELtPyBHqXGxmvbCg1xD/GoXTJcP4gki8pVTK3G302DEEXJh3zIt6ziHNoEAcX8OtgD6oGPHGpqrNKYu6aLtPpdYFhPtG3uF6CmD4qoR+1+FlQnORUmnRYPLyHUKEzVrCae6Q1N16GbA9jEzLCIVYZITLw3bbkVMcgwRpxGw6jwivawmShVulQQ6aeN6oX+wsxni0d8gVOtpOvUKOZw8tiHGA7M3PoHdR+uD1e3h3+25RIGvhub64TPGSBPet4EG1Vw==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
