apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: traefik-gateway
  namespace: default
spec:
  gatewayClassName: traefik
  listeners:
    - name: web
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All
    - name: websecure-traefik
      protocol: HTTPS
      port: 443
      hostname: traefik.koutoulastha.dev
      tls:
        mode: Terminate
        certificateRefs:
          - name: traefik-koutoulastha-dev-tls
            namespace: default
      allowedRoutes:
        namespaces:
          from: All
    - name: websecure-argocd
      protocol: HTTPS
      port: 443
      hostname: argocd.koutoulastha.dev
      tls:
        mode: Terminate
        certificateRefs:
          - name: argocd-koutoulastha-dev-tls
            namespace: default
      allowedRoutes:
        namespaces:
          from: All