---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: truenas-exporter
  namespace: monitoring
spec:
  encryptedData:
    api-key: AgAgrwBNFuuNXzma5YRHHj1+oIw/HE3ybP2Z+h9lD9vBQy8SWdGW6TQroMC4wmdb8DOsea3rnHfO4m+MxZxYukw6TBSbLPXjIVyMym4thoTpNRXe0W5/pVfdceaj4SwIEv9kg6YYoRb3nne7Mpy6EQApy7zTtZur3m1Z7S6o6KGYpft+pgQKajoXSEjYAr5lwaejQRszfZgiuowKnwAem3YNeCMAzGpH+dvAxNAvznsVI4lrpKFa1arM1Woyd6oTi53ZsOrJIVBPiea1PcrV5rlciqspuVkT4ZX+cLg8d+O2Q8uSaKUleGR8OaTseiYMzu5rDZntotTEW3FJCF6MRzXmPzmfpmKmoyxIG6W47yB629HD6eE/dw0/SCNwAV3vGi5UwzlUjAStflywK/E/zT5PCbR2gPmOsMiYr0w5m5K1Vwd0kvyQesx+1rxbag5L/9mSkvY1ap6vvsblcDuWr5AdICWOCaofY71lEN2edk2n4l0sSSySh+2M45uOl+gaQhlzZZ0QyW0/vDD5r7zXcJO9IFFdf0RJt/CvipLTYGbYMqaNbjRORbLfoIQJVboGuyFafJcTmoBLzqVkpGuWPnRiTOsYwUah6QeX1pweVl0tMVgcRTzprwg7+d+Lrq1iyv2YDEw8d+2BddJPp4xkW38KRqRNjsuxTVmZQf0D8UyGUznbFPO/Hp6VR3VweVgnr73XE3260L/3FxSf6Irsq5q+ILq3XmRAz2qIyCxKhV0EysIOtOML78YQaE7QtoosQT/yhMiSu3ieAdn5oR+lOmB0H0A=
  template:
    metadata:
      name: truenas-exporter
      namespace: monitoring
