---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pve-exporter
  namespace: monitoring
spec:
  encryptedData:
    pve.yml: AgDBq4fq2lKOy3FX/4Xg+2TeW5xkh593EPVdw0pCUoTJrdTlnmNm+1VCsiHw8sN2CQk/NmZbHQyolBVY/9/LXuuVtCG1Pf3mIPAx9XKPyRGJYRPEvbLoDdTChjxDJSu/UzsRrM5iEL/TdSP5iL8NjPJG7PEH/xzK3pylWxSHsZUJTf6Xv9aNIazkM+TmkqPm+0F7M4i9QdoQ0Kbx12vwsOuchxJszW22x7k2M6hjTrS4fp32c9taojIjU36pXS/YxvyJf3KIZpGwrHSohjtFHbrS2mc/t1N+22HPqIF76rjdgpjoIyi8z7hKvD0Onn4b0YIqN9PXqg0XXMtCfJw8HoxMDoffxLrgxludU1NuOJylNBpfiVnAw+4FMMDgjkUU0tbJ7wajgAOXwgdfmgofq95akM23uspoVXP/fM5+bO4wECSnGYlOeNvh5i0Oavt33LUiI36KGOOULcheyJs9MGJX1SLWh6ie90fv7T1aytbRmhZd4BJ7g/EnIhbLFR6yzKxDaV/xm2J/YNU5KcQFtBe8JhNTVwXOVXth2a7onne8CG6c3DtmqceXwsRP39vFMJ0ex33Nv/CKjakYZKhIMo5vIC7pxiEK0p4ldxZYQwuM5Eoai2rRmSEBmHJWr09KkpCZ6PZz39I2eGc8ZXLCFm2V5MPOMA+SjpnKNW5p6/9woq3Cl6Owp8AwVuMVAZ1gztjKtMwB7Dn8S3SHNLZP4DWFbKOyuxCJL8eEq6Hd1PoXTIm48XWX0U4otLuZoFOoE0RvHz11M/P6KlA/d8n8X7XPl/m4eCQvis70Qlz92tGNL77jpgeE++/B7wHxBqV1aGEfZAdzG4yFf6NFurXz5+R01I7g6bnU0kzGxd7aRFKZAQ==
  template:
    metadata:
      name: pve-exporter
      namespace: monitoring
