apiVersion: v1
kind: Service
metadata:
  name: pve-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: pve-exporter
spec:
  type: ClusterIP
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster
  selector:
    app.kubernetes.io/name: pve-exporter
  ports:
    - name: metrics
      protocol: TCP
      port: 9221
      targetPort: metrics
