apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pangolin-newt
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: pangolin
  sources:
    - repoURL: https://charts.fossorial.io
      chart: newt
      targetRevision: 1.4.0
      helm:
        valueFiles:
          - $values/apps/pangolin-newt/values.yaml
    - repoURL: https://github.com/koutoulastha/home-lab.git
      targetRevision: version3
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
