apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  sources:
    - repoURL: https://traefik.github.io/charts
      chart: traefik
      targetRevision: "*"
      helm:
        valueFiles:
          - $values/infrastructure/networking/traefik/values.yaml
    - repoURL: https://github.com/koutoulastha/home-lab.git
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-config
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    repoURL: https://github.com/koutoulastha/home-lab.git
    targetRevision: main
    path: infrastructure/networking/traefik
    directory:
      include: '{httproute.yaml}'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true