apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: democratic-csi-iscsi
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: democratic-csi
  sources:
    - repoURL: https://democratic-csi.github.io/charts/
      chart: democratic-csi
      targetRevision: 0.15.1
      helm:
        valueFiles:
          - $values/infrastructure/storage/democratic-csi/iscsi/values.yaml
    - repoURL: https://github.com/koutoulastha/home-lab.git
      targetRevision: version3
      ref: values
    - repoURL: https://github.com/koutoulastha/home-lab.git
      targetRevision: version3
      path: infrastructure/storage/democratic-csi/iscsi
      directory:
        include: 'sealed-secret.yaml'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/enforce-version: latest
