---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sonarr-secret
  namespace: media
spec:
  encryptedData:
    SONARR__AUTH__APIKEY: AgByolDOoBfjNV+TJX+a//qjlAhpB7ghdzjEPSwzdGo8vhuulgA6qZYhHZ0exiNL18FyB3BGL49nT/BWUcl8ssjonQLnOaOKV1ssde6jxFd8Wmy9ewfsUT18nX34mVPJAerNKfUn7//I6QLpVrNl6RK6ZnqhZn4iAUpcRqqz5M1l0g0h2o7VBuxczV87xdnQAGOFUyaM5w2uNQc32v0t7Lk5HLISpqggxGPetl4jccbbV/GzFoV1djRYemyHjxsDXlcXEnwtY0q1muJ+vm9KQmJrUqh6a8NhKj41S4VKrWwKXwGbBwpQUUfhPJ9qy7/Hyn3mgnuDzXmS0e+35sIYv5BjCmJmhavXxc4j7RCjzWFVgsbGCs9JNuikkj/6KJORcZ1/cgvjXgt097vtyveQFFXXfl0bVMuc4aBy8bm1Nf7woUsjlPhcvuopvfMpTWlE9b3+N/2ul8DcuvuBFNZQMirS8nMyNwTgBO2kvMX1t3t3ccv2n6u7sqWwpl8YA/qRtlvbbN4ErDO38ZxsPFiiXZL5MYdKJCGPnes9TSK8JJqWzfFOUYA2bYg7YAjzAJ6rks8KAqzrD8oXw8s6D0WRRNsj6ZNez9+Ghce7YvdFC/7E6nR8sYqppzsFihuWBjn9Xuyw6l20LgJKyl6tQwdhd8EfkkPXsMDWZE7T6xz/38WaLRDOuzoKq0y9jA2AwBzsq3htstEgbFtDMiHq6RqvS0Sdeg8QoPweGE+AQzHp5tlP2A==
  template:
    metadata:
      name: sonarr-secret
      namespace: media
