---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: loki-push-auth
  namespace: monitoring
spec:
  encryptedData:
    users: AgCSdh83719zXE9LniL0NyxDbD3NJVfS2jm9xtgMS7Il/M9YlEvbt76Vb2KY0Hp/4iX/7PgN77WV3DBTfBFGD0Xp1LtDOzjneU/6chuQKL4BnI9/wPaP22Bfskq4awN43zHPeHbxLCVrcoPR8AP8+ScyNAiJMq6X1oDC8r0XeifYStCHLZApbFbqnmkKOa8D6pp4Y00y3Vjiy5KeViskPlQ5zBMtjEGoOZe1cLU1qpn0vcIU0Ocqx39xTwoEOueaDIG2yOro/8C24lijutuSRAqkpVvaxGewKE5Rrd57nZmTVdHY0Za0Zv6UlE4DY/LQdWEOqSOoOWiGMdhwM30zLqfeR4J71NSWeyZg9hRLll0dZsjni+VRmXq5/DLZHr1PtJMkzGecD4dIm1rVLj3MnXOWbgspVAw93un6616tx4J2BU2WPX0yeLNERrDS6n58H3uZcGklQDZZwQ9N+EoB7pEtTt5vD/l6rhXDr56dPRg4qFEMT5lzZvzNgq3PToB0pVNpK4DyeWf0Wa9/uTPVw6QnQCGu2VSFyA7+726ehwH7KqtRlUQvC27c29/2Uu5qTdgjcVyF+JPwbOwuokG7PazeUhMno8t1IOYWxODqU5N7q5YeRM4HstGrWgrcX0+v4ppWrcws9GWA/FiAJYdgKtZn63WtxTix6Jc/QzsWibYrklFIoNhw/p1Ye0UY6ZNvMOkJo5i8vNDXu8nHN9VlN+E3FfIGJXM0zuDXllUhVrOpRGxvFEiTBAd2lgnqDAkWgiQLagI+uzTPF87HzZn2DB9uu8JZ
  template:
    metadata:
      name: loki-push-auth
      namespace: monitoring
