---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: loki-push-auth
  namespace: monitoring
spec:
  encryptedData:
    users: AgC20eNOzFhsCQhUZBNAa67lVJyB10QFXCR0AuexqFLaeWk0Vt+O5apnrKveaf40laXvdBiQlABEpiB7GCwGV3/MsIR4E9e4XYBGlJwMBOnebUVFjEtWY6jaMOlRj8KgBaPYHvCYeztTU1m1ROW4SK/yDvsLufzkpi7nxUAU4f1cXxRjmGGx3nNBrNYcWOKei8gjTVgTrCU2/cJXDhWmru7YEC6bOitqkJR/TlXJWnS7+MD6vRiMNfoKWFr4A8hFkdQPGqrqWbcb0VLdkKqcVgpJFAG/kvX7VdQX7HmaoLIOzhM+Grcqv3JvdxYzYVfOFbc0hoLzzkN6zrxORXrHNofrRLM8FAAIoj5nODkNkAS1MSAvOyjKYnFlNj6zdAQaORn10aH+vclMhuJWI7uSfKmwmbunsI/FgEV1MeMb6AaPZ1qd8APjcvo49wTPt9h2jLecXuHfMH4VLH9aUiCfQtkofR7Akdpnkmu0yFA2xtWGTlxUG0yNCRw0Q8QAOdNCPmQAvbmEFeIIvZXFV82yfyVe76GlRopEPFmNCFvNEJ2Gu46t0jwFQCBb54DNigqsS7PJ1b+AnhNH2pfwKYULe9NqH0Ygd+Lid4Uz/a2mEGhTRfovaw1kEqiZcxHNJg8jN5E0c8j8tjnzTBFYcOjxcazrDpmtCRlVjj+uA4GiqOqskxt1o7VnSIEvjJPGXkpp7VrPTDqPEb7jMBX/Sl67IkHgh4zHBP+WAwuydqrrqtf/x90YfyyIpQyaNQb+DHMWAJFXXyS8RRGPSAhc1qE+O81bG0vp
  template:
    metadata:
      name: loki-push-auth
      namespace: monitoring
