---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gluetun-proton
  namespace: media
spec:
  encryptedData:
    WIREGUARD_PRIVATE_KEY: AgDCY7nEwmOdOy/33cEZGsnJS0lPemc0wnwqGAFFJEVyx0AQMqRpUj35mJ9ZSyiDgsvwTvJPbWGW2ToWwyStx5BA+46c2EtSUH78CNLQptrMEviFH1TxgqRFrwz8aHi1BtOSrtlSw6AYw+PlAqd3GE82L3k3JxRzWzuPFIH3lMqtU9O7knwspogZA/Yo/F7VblTpu9KxjziAU0tsGUvJsJm+sI+M9vydi/xj2vuBvY2UJ3gaXEod9HBY8ZallFYPFqL8HAW/azBBcOPec6vSI2nDBoWO+DGyH+u5Fl3uRocbvg1hGgPoXp1cetV9sv6AI9WJKHnBfQoSKv0aXVYyUBfwuMm4w0XzEj9Y02Lg4qnSw7EBfYEjDEh1zJ+2MV8eyYNBJRQg3mck5vYPL9L4g+KN+AxxkDQXtUz01eZ/XtZldEJyCv1NRpDQHhRY/4vsrLDeUJdrMf8wjNz0qK2wwr4Uhojc4h5p0ZP1zrsjg8pl5XmIxrHhGeAJzy0y4qHuGFCEO00bR6to4APmUhWVvDLPMptAn1aodHvMSOPDlwkhQQm9XELEn5sNCQmUx0AIq3SpTMeW6bF91rg7kd/S/7HjFn+G6kFLd//rKs9ggSiY/lfV+ikFlawvf6xu1gwx7hwKfKBd4PIkxajyPsYmXExoOZmsZ5Y/LzIuz4Gd0RHOrMT4oW8aDotZicwEslTZYTIpusGMV+6IByrkBXcBLzsZh2XTJS3tLpveV/idTeTzZqdj1BUG0RXIdVbhbw==
  template:
    metadata:
      name: gluetun-proton
      namespace: media
