---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: radarr-secret
  namespace: media
spec:
  encryptedData:
    RADARR__AUTH__APIKEY: AgCaTpmfR+9dKZnoqySCGebEvYsVvRIysvBs7mc9swDyXHTD057uqkQMgoQonBIx2ZLGqQzVzGk7Uz1V+6/TQnjtrd4tao2aRmpbXi/F75sR3QdUDBjPl4raThCkpPqUrHcpl769fNFMTL+mP3mIXp13SkDKrmayHujEq69BL7SupzfqvCisHLlPy13fo38hasf5wTV2eOrbXDAG+VruUWK07fQQp9V7sQC6vwCsIYNKC0PO/w96cgIggZWmW3TNA/mzw/8T2sAH15xxqPnAceMTddq0PsnIFlp2f45sdG8bRYSdXtDBCpjcMRmSM6pnkSRoV0EOeP4Q8bD41bnJoBj5Hs6F4XBdTlT7rIFO1xHtavzkYN1cWYHYnqAY0TqTQr0a2n18OLjNdJTj+IE1wvKypjjXLtrdfPgIC0qVQDnf7MOxB1mKw1VEbPOJ7S3u9yiWYP9qjDdsl3xhFEYJSu3fflD7IsyPXDOqyIxuWWkLy6Bh32TCIkLkfiD1sJc/yd3m/o/wSfHCyR0vVJBIJBwWUzH2kRGZ1m2qUmbFugbU1o7LJn/lrU7iRNWlV4MLlLNXDc463HhUkOPKYIzu0jHr5rMp1OEOVX1yMVxccFPebopq0glieHpPPA5L+7bpbzRDEnrlJEpEzThY7IjDFMpTXJHAHdI52MBLHUgZQkNjfyP37KA1YQJXFMnVhnqKOwoQe8TJMsDsZIJByyhoJ2tIZknPa7yEcPmBIw9c9GNFgg==
  template:
    metadata:
      name: radarr-secret
      namespace: media
