---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: prowlarr-secret
  namespace: media
spec:
  encryptedData:
    PROWLARR__AUTH__APIKEY: AgC1a4XXymffhJYhNx3SK3mpEj0XFRdNIhzAynWqiwHi3bvOTvQYPftkvQsd95ouViYWgANgMjDADIUHhryuQFliD5A+GIYCcvmJrNFJcJLKRpvccOnNmvMPhHNHsKRaH28L00QqdsCmnz+womF+wCzBkx7lSrJibK+KZMejeT+LHTLu4A8oCQ0oTkEebjbmHrJDyKkBqyN61xxDI1iO5FnkIukzps0HtxnnqCZLqceKlfMzWxUUIL1Aw8dmo1d8W6kHrW7pMYtWf0ZSaPMLiFF+XGnWwgkSsijc6V0dVq83KYMC2yhlFooQcix5udKpws9XYH/9wQ4HvCbx/yo1IcB5D8YZE0viFWkV1tvukqd1mzotc3qEdVP/Nc/e7bycmKfHR3Sdv+8ssjKO+cw2n7Rb5VOg7VqgBuaqku7OZpvLcS7BJ4tLeWro7Hq4V+AjlVfUKB0BmVtAsnRco1cINMsheH8oJI8RU4oyloXfMxvwCTSoAFtoE5051ZH9xdUs8r09eVFR2U3+8OHk2LnPmXmCXcXjcoNNuHzDeN1KjCRxInfcFvxHyeHlhKIeW1bXDfUn9IDwHB4otPXw29xBpeJdw9qyMS4jk9VnCq7SdRvd6eybR7pTaXV+W2d6MqQRhETReBALDedl67QaxRJyqM4QExkJ2TNZmvGNd3fWb5B7qBpsBVZK8QRDJy04Vz0EwGS3ALoJ+c+m2tRU0Q9M+U8J7tbJBUAD33fCToCM1RqzNg==
  template:
    metadata:
      name: prowlarr-secret
      namespace: media
